apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myappset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: staging
        url: https://kubernetes.default.svc
      - cluster: production
        url: https://kubernetes.default.svc

  template:
    metadata:
      name: '{{cluster}}-myapp'
    spec:
      project: default
      source:
        repoURL: https://github.com/adityaraj178/test1.git  # Change to your repo
        targetRevision: HEAD
        path: "."  # Change if needed
      destination:
        server: '{{url}}'
        namespace: myapp
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true

